version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:docker pull circleci/ruby:2.4-stretch-node-browsers-legacy

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date
